version: '3.8'

services:
  redis:
    image: 'redis:latest'
    container_name: 'redis-server'
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data
    restart: always

  postgres:
    image: 'postgres:latest'
    container_name: 'postgres-db'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
