// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	DATABASE_URL: stirng;
	FRONTEND_HOST: string;
	CF_TURNSTILE_SECRET: string;
	SUPABASE_URL: string;
	SUPABASE_SECRET_KEY: string;
	WEBSOCKET_COUNT_SERVER: DurableObjectNamespace<WebSocketHibernationServer>;
}
