name: Deploy
on:
  push:
    branches:
      - main
jobs:
  migrate-db:
    runs-on: ubuntu-latest
    name: Migrate Database
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Run Migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push

  deploy-worker:
    needs: migrate-db
    name: Deploy Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          command: deploy --compatibility-flags="nodejs_compat"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: backend

  deploy-frontend:
    name: Deploy Frontend
    needs: [deploy-worker, migrate-db]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
        working-directory: frontend
      - name: Build
        run: npm run build
        working-directory: frontend
        env:
          PUBLIC_BACKEND_HOST: https://api.counttoamillion.com
          PUBLIC_BACKEND_WEBSOCKET_HOST: wss://api.counttoamillion.com
          PUBLIC_CF_TURNSTILE_KEY: 123,
          PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: f24d1f62bfe4b558707bd595d5b952da
          workingDirectory: frontend
          branch: main
          projectName: counttoamillion
          directory: dist
          wranglerVersion: '3'
